### ISSUE TITLE
Crashing on save with this mod enabled

### ISSUE THREAD

**Issue by nmbooker** [MacSergey/NodeController30#22]
Version: 3.0.3.1
Harmony version: 2.0.0-4
OS:
```
$ uname -a
Linux ogg 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I have only one other mod enabled at the moment:
 * TM:PE 11.5.2 STABLE

I don't have to have modified any nodes or inserted any crossing using NodeController, simply loading harmony and Node Controller, loading the game and saving it again is enough to reproduce it.

My Player.log at point of save looks like this:

```
[NodeController] Start save map data
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[NodeController] Save map data failed
SIGILL
  at (wrapper managed-to-native) System.IO.Compression.DeflateStream:CloseZStream (intptr)
  at System.IO.Compression.DeflateStream.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Close () [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Dispose () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Stream:Dispose ()
  at System.IO.Compression.GZipStream.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Close () [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Dispose () [0x00000] in <filename unknown>:0 
  at ModsCommon.Utilities.Loader.Compress (System.String xml) [0x00000] in <filename unknown>:0 
  at ModsCommon.Utilities.BaseSerializableDataExtension`2[TypeExtension,TypeMod].OnSaveData () [0x00000] in <filename unknown>:0 
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ExecutionEngineException: SIGILL
  at (wrapper managed-to-native) System.IO.Compression.DeflateStream:CloseZStream (intptr)
  at System.IO.Compression.DeflateStream.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Close () [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Dispose () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Stream:Dispose ()
  at System.IO.Compression.GZipStream.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Close () [0x00000] in <filename unknown>:0 
  at System.IO.Stream.Dispose () [0x00000] in <filename unknown>:0 
  at ModsCommon.Utilities.Loader.Compress (System.String xml) [0x00000] in <filename unknown>:0 
  at ModsCommon.Utilities.BaseSerializableDataExtension`2[TypeExtension,TypeMod].OnSaveData () [0x00000] in <filename unknown>:0 
Rethrow as ModException: The Mod /home/nick/.local/share/Steam/steamapps/workshop/content/255710/2472062376 [CitiesHarmony.API.dll, System.Xml.Linq.dll, NodeController.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll, NodeController.resources.dll] has caused an error

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
SerializableDataWrapper:OnSaveData()
Data:Serialize(DataSerializer)
ColossalFramework.IO.DataSerializer:Serialize(Stream, Mode, UInt32, IDataContainer)
<SaveSimulationData>c__IteratorC:MoveNext()
AsyncTask:Execute()
SimulationManager:SimulationStep()
SimulationManager:SimulationThread()
 
(Filename:  Line: -1)

Saved simulation data to: /home/nick/.local/share/Colossal Order/Cities_Skylines/Saves/Temp/5753aa54-9453-45b2-bd77-a2cbf435b0e0.ccs  [Serialization]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Adding package 'testsave-nodectrlr' [Transient]  [Packer - Internal]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Saving package to cloud 'testsave-nodectrlr' [Transient]  [Packer - Internal]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Refreshing package 'testsave-nodectrlr' [cloud:testsave-nodectrlr.crp]  [Packer - Internal]
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

**Comment by nmbooker** [comment]
I started a brand new game with all mods and custom assets disabled except NodeController and Harmony, and this happened at the end of the load as it showed the map in an 'AN ERROR OCCURRED' dialog:
```
Object reference not set to an instance of an object
[System.NullReferenceException]

Details:
No details
```

Funnily enough NullRefrenceExceptions were what were initially happening on save, but then when I started following the log file I got the more detailed exception from the description instead.

No wonder the inventor of the null pointer said it was his biggest mistake ever - but languages keep on supporting the things anyway.

**Comment by nmbooker** [comment]
Some more investigation:
* Disable all mods and assets in Content Manager
* Create a new game (I used the Black Hills map) with drive on left enabled
* Save the brand new game as 'test-newgame-save-nodectrlr'
* Quit -> To Main Menu
* Content Manager: Enable Harmony mod
* Load the saved game
* Save game again (overwriting the previous save)
* Quit -> To Main Menu
* Content Manager: Enable Node Controller Renewal mod
* Load the saved game
* Save game again (overwriting the previous save)

At this point the whole game crashed.

Parting log entries were:
```
[NodeController] Start save map data
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Receiving unhandled NULL exception
#0  0x007fd468ffdf00 in funlockfile
#1  0x007fd468ffe4b8 in (Unknown)
```

That's the original error I was going to report.  I don't know how and why the other one started coming in - perhaps I'd loaded a partially-saved game file?

**Comment by MacSergey** [comment]
https://github.com/MacSergey/NodeMarkup/issues/96
